# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodGame
  pod 'Parse'
  pod 'AlamofireImage'

  target 'FoodGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodGameUITests' do
    # Pods for testing
  end

end
